server:
  port: 8080

amadeus:
  api_key: 'GeARJeG500qYFqhPeYYL5Z8qRFlfnAbu'
  api_secret: 'S2bblGKWK18UeXwd'
  environment: 'test' # or production
  loglevel: 'debug' # or warn

spring:
  datasource:
    url: jdbc:h2:file:./data/airport
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    spring.jpa.defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false
    spring.h2.console.settings.web-allow-others: false
